#!/bin/bash

set -e

service mysql start

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CHANGE MASTER TO MASTER_HOST='$MASTER_HOST', MASTER_PORT=$MASTER_PORT, MASTER_USER='$MASTER_USER', MASTER_PASSWORD='$MASTER_PASSWORD', MASTER_AUTO_POSITION=1;"
# mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SHOW SLAVE STATUS\G;"
